apiVersion: v1
kind: Pod
metadata:
  name: database-node5
  labels:
    name: database
    node: node5
spec:
  containers:
    -
      name: database-node5
      image: paunin/postgresql-cluster-pgsql
      env:
        -
          name: "REPLICATION_PRIMARY_HOST"
          value: "database-node4-service"
        -
          name: "NODE_ID"
          value: "5"
        -
          name: "NODE_NAME"
          value: "node5"
        -
          name: "CLUSTER_NODE_NETWORK_NAME"
          value: "database-node5-service"
        -
          name: "REPLICATION_UPSTREAM_NODE_ID"
          value: "4"
      ports:
        -
          containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database-node5-service
  labels:
    name: database
    node: node5
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database
    node: node5